name: flutterlib_example
description: Demonstrates how to use the flutterlib plugin.
publish_to: 'none'

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_markdown: ^0.3.2
  video_player: ^0.10.5
  # 路由框架
  fluro: ^1.5.1
  image_picker: ^0.5.0
  sqflite: ^1.1.5
  url_launcher: ^5.0.2
  # 本地存储、收藏功能
  shared_preferences: ^0.4.3
  dio: ^3.0.9
  path_provider: ^1.1.0
  firebase_analytics: ^1.1.0
  flare_flutter: ^2.0.3
  flare_dart: ^2.3.4
  extended_nested_scroll_view: ^0.4.0
  flutter_swiper: ^1.1.6
  flutter_spinkit: ^4.1.2+1
  event_bus: ^1.1.0
  loading: ^1.0.2
  # Toast插件 https://github.com/OpenFlutter/flutter_oktoast
  oktoast: ^2.3.2
  # Dart 常用工具类库 https://github.com/Sky24n/common_utils
  common_utils: 1.2.1
  # Flutter 常用工具类库 https://github.com/Sky24n/flustars
  flustars: ^0.3.2
  # 图片缓存 https://github.com/renefloor/flutter_cached_network_image
  cached_network_image: ^2.2.0+1
  # 格式化String https://github.com/Naddiseo/dart-sprintf
  sprintf: ^4.0.2
  lpinyin: ^1.0.7
  azlistview: ^0.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutterlib:
    path: ../

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/image/
    - assets/flare/
    - doc/
    - lib/demo/
    - lib/demo/horizonal_scroll/
    - lib/demo/draggable_btn/
    - lib/demo/pinned_sliver/
    - lib/demo/pinned_sliver/component/
    - lib/demo/popup_window/
    - lib/demo/search_input/
    - lib/demo/video/
    - lib/demo/video/component/
    - lib/demo/banner_widget/
    - lib/demo/test_widget/

    - assets/data/china.json